#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers
obj-$(CONFIG_SENSORS_AK09911)   += akm09911/
obj-$(CONFIG_SENSORS_CAP1106)   += cap1106/
